include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
#  language:
#    strict-raw-types: false
#  strong-mode:
#    implicit-casts: true # activate with false
#    implicit-dynamic: true #activate with false   
  errors:
    uri_has_not_been_generated: ignore
