name: bson
version: 5.0.0-4.0.dev

description: Bson library for Dart programming language. BSON, short for Binary JSON, is a binary-encoded serialization of JSON-like documents.
homepage: https://github.com/mongo-dart/bson

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  fixnum: ^1.1.0
  decimal: ^2.3.3
  rational: ^2.2.2
  uuid: ^4.1.0
  packages_extensions: ^0.1.0
  power_extensions: ^0.2.0


dev_dependencies:
  test: ^1.24.6
  lints: ^2.1.1

